"""
automorphism_centralizer_extended.py

Phase 3: enumerate the full Lie subalgebra of operators on the
extended per-site C^12 amplitude that commute with the bipartite
tick rule, and compare to the 18-dim direct sum
so(3,1) (+) su(3) (+) su(2) (+) u(1) proposed in Eq.~(137) of
Paper I.

Structural setting.

The bipartite tick rule on C^12 is
    T_ext = is * I_12 + c * (sigma_x (x) I_2 (x) I_3),
where s = sin(delta_phi/2), c = cos(delta_phi/2).  For an operator
X on C^12 to be a per-site automorphism of the lattice dynamics
(equivalently, [X, T_ext] = 0 for all delta_phi), the constraint
reduces to
    [X, sigma_x (x) I_2 (x) I_3] = 0.

Using the tensor-product basis of su(12) generated by
    {sigma_a, I_2} (x) {sigma_a, I_2} (x) {lambda_a, I_3}
(minus the all-identity, total 143 traceless generators), a basis
element A (x) B (x) C commutes with sigma_x (x) I_2 (x) I_3 iff
[A, sigma_x] = 0, i.e., A in span{I_2, sigma_x}.  The centralizer
has dimension

    dim = 2 (chirality {I_2, sigma_x}) * 4 (isospin {I_2, sigma_a})
        * 9 (colour {I_3, lambda_a}) - 1 (trace)
        = 2 * 4 * 9 - 1 = 71

in su(12), or 72 in u(12) (including the trace = overall U(1) phase).

What this script verifies.

  Step 1: confirm dim(centralizer) = 72 in u(12), 71 in su(12).

  Step 2: identify which of the 14 Hermitian generators of the
          conjecture's 18-dim algebra are in the centralizer:
            - J_1 = (1/2) sigma_x (x) I_2 (x) I_3      (in centralizer)
            - J_2, J_3 = (1/2) sigma_{y,z} (x) ...     (NOT in)
            - 3 SU(2)_W: I_2 (x) sigma_a/2 (x) I_3     (in centralizer)
            - 8 SU(3)_c: I_2 (x) I_2 (x) lambda_a/2    (in centralizer)
          So 12 of 14 Hermitian conjecture generators are in the
          discrete centralizer; J_2 and J_3 emerge only in the
          continuum O_h-averaged limit.

  Step 3: characterise the "extra" 71 - 12 = 59 traceless
          generators that commute with the tick rule but are NOT
          in the conjecture's su(3) (+) su(2) (+) <J_1>
          subalgebra.  These split as:
            - 24 isospin-colour mixings (I_2 (x) sigma_a (x) lambda_b)
            - 3  chirality-sigma_x x isospin (sigma_x (x) sigma_a (x) I_3)
            - 8  chirality-sigma_x x colour (sigma_x (x) I_2 (x) lambda_a)
            - 24 chirality-sigma_x x isospin-colour mixings
                 (sigma_x (x) sigma_a (x) lambda_b)
          Total 24 + 3 + 8 + 24 = 59.  None of these are gauge-
          invariant in the SM sense: they all mix factors that the
          conjecture treats as independent.

  Step 4: report the structural conclusion.

Phase 3 outcome (predicted, confirmed by this script):

  STRICT CONTAINMENT.  At the discrete Hermitian level,
  Aut_ext_centralizer (= operators commuting with T_ext) has
  dimension 71 in su(12), strictly larger than the 18-dim
  direct-sum subalgebra of Eq.~(137).  The 59 extra generators are
  tensor-product mixings between the conjecture's factors -- they
  commute with the tick rule but are not consistent with the
  conjecture's factor-product structure.

  Whether these 59 extras survive the continuum-emergent
  restriction (Lorentz from O_h-averaging, basis-permutation
  symmetry on the colour C^3, and any other lattice-level
  structural constraint we have not enumerated) is the open
  follow-up.  For Eq.~(137) to hold as exact equality at the
  continuum level, the 59 extras must be killed by some natural
  continuum-emergent constraint -- a constraint we identify but
  do not impose in this script.

  Audit-table row: PART, with the structural caveat that the
  containment $\supseteq$ from prior PASS rows is confirmed and
  sharpened, but equality $=$ requires constraints beyond the
  per-site centralizer test.
"""

import sympy as sp
from sympy import I, Matrix, eye, sqrt, simplify, Rational


def pauli_matrices():
    sx = Matrix([[0, 1], [1, 0]])
    sy = Matrix([[0, -I], [I, 0]])
    sz = Matrix([[1, 0], [0, -1]])
    return [sx, sy, sz]


def gell_mann_matrices():
    L1 = Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 0]])
    L2 = Matrix([[0, -I, 0], [I, 0, 0], [0, 0, 0]])
    L3 = Matrix([[1, 0, 0], [0, -1, 0], [0, 0, 0]])
    L4 = Matrix([[0, 0, 1], [0, 0, 0], [1, 0, 0]])
    L5 = Matrix([[0, 0, -I], [0, 0, 0], [I, 0, 0]])
    L6 = Matrix([[0, 0, 0], [0, 0, 1], [0, 1, 0]])
    L7 = Matrix([[0, 0, 0], [0, 0, -I], [0, I, 0]])
    L8 = (1 / sqrt(3)) * Matrix([[1, 0, 0], [0, 1, 0], [0, 0, -2]])
    return [L1, L2, L3, L4, L5, L6, L7, L8]


def kron(*mats):
    r = mats[0]
    for M in mats[1:]:
        r = sp.kronecker_product(r, M)
    return r


def commutator(A, B):
    return simplify(A @ B - B @ A)


def is_zero_matrix(M):
    return all(simplify(e) == 0 for e in M)


def tensor_basis_su12():
    """Enumerate the 143 generators of su(12) as tensor products of
    Pauli matrices and Gell-Mann matrices.  Each basis element is
    labelled by its tensor signature (chirality_factor, isospin_factor,
    colour_factor) for later classification.

    Chirality factor: I_2 (label 'I') or sigma_a (labels 'X', 'Y', 'Z')
    Isospin factor:   I_2 (label 'I') or sigma_a (labels 'X', 'Y', 'Z')
    Colour factor:    I_3 (label 'I') or lambda_a (labels '1'..'8')

    Excludes the all-identity tensor (which is the trace, not in su(12))."""
    sx, sy, sz = pauli_matrices()
    L = gell_mann_matrices()

    chirality_options = [
        ('I', eye(2)),
        ('X', sx),
        ('Y', sy),
        ('Z', sz),
    ]
    isospin_options = [
        ('I', eye(2)),
        ('X', sx),
        ('Y', sy),
        ('Z', sz),
    ]
    colour_options = [('I', eye(3))] + [
        (str(a + 1), L[a]) for a in range(8)
    ]

    basis = []
    for (cl, C) in chirality_options:
        for (il, IS) in isospin_options:
            for (col_l, COL) in colour_options:
                if cl == 'I' and il == 'I' and col_l == 'I':
                    # Skip the identity (= trace, not in su(12))
                    continue
                basis.append({
                    'chir_label': cl,
                    'iso_label': il,
                    'col_label': col_l,
                    'matrix': kron(C, IS, COL),
                })
    return basis


def commutes_with_tick(elt, Y):
    """Check whether a basis element's matrix commutes with Y =
    sigma_x (x) I_2 (x) I_3."""
    c = commutator(elt['matrix'], Y)
    return is_zero_matrix(c)


def classify_element(elt):
    """Classify a centralizer element by its tensor signature."""
    cl = elt['chir_label']
    il = elt['iso_label']
    col_l = elt['col_label']

    is_iso_id = (il == 'I')
    is_col_id = (col_l == 'I')
    is_chir_id = (cl == 'I')
    is_chir_X = (cl == 'X')

    # Conjecture generators
    if is_chir_X and is_iso_id and is_col_id:
        return "J_1 (chirality rotation in conjecture's so(3,1))"
    if is_chir_id and not is_iso_id and is_col_id:
        return f"SU(2)_W generator T_{il}^W"
    if is_chir_id and is_iso_id and not is_col_id:
        return f"SU(3) Gell-Mann lambda_{col_l}"

    # Mixings (extras)
    if is_chir_id and not is_iso_id and not is_col_id:
        return f"isospin-colour mixing  sigma_{il} (x) lambda_{col_l}"
    if is_chir_X and not is_iso_id and is_col_id:
        return f"chirality_X x isospin  sigma_x x sigma_{il}"
    if is_chir_X and is_iso_id and not is_col_id:
        return f"chirality_X x colour  sigma_x x lambda_{col_l}"
    if is_chir_X and not is_iso_id and not is_col_id:
        return f"chirality_X x isospin-colour  sigma_x x sigma_{il} x lambda_{col_l}"

    return "unclassified (should not occur for centralizer elements)"


def report():
    print("=" * 70)
    print("Phase 3: discrete-level enumeration of the per-site C^12 centralizer")
    print("=" * 70)
    print()

    sx, _, _ = pauli_matrices()
    Y = kron(sx, eye(2), eye(3))

    print("Tick-rule constraint: [X, Y] = 0 where")
    print("    Y = sigma_x (x) I_2 (x) I_3.")
    print()
    print("Tensor-product basis of su(12):")
    print("    chirality {I_2, sigma_a}  *  isospin {I_2, sigma_a}")
    print("      *  colour {I_3, lambda_a},  minus the identity.")
    print()

    basis = tensor_basis_su12()
    print(f"Total su(12) generators (tensor basis): {len(basis)} (= 143).")
    print()

    # ── Step 1: compute the centralizer ────────────────────────────────
    print("-" * 70)
    print("Step 1: centralizer of Y in the tensor basis")
    print("-" * 70)
    print()

    centralizer = [e for e in basis if commutes_with_tick(e, Y)]
    print(f"Number of basis elements commuting with Y: {len(centralizer)}")
    print(f"(Predicted: 71 in su(12), matching dim u(6) (+) u(6) - 1 = 72 - 1.)")
    print()

    # ── Step 2: identify the conjecture's generators in the centralizer ──
    print("-" * 70)
    print("Step 2: which conjecture generators are in the centralizer")
    print("-" * 70)
    print()

    in_centralizer = {
        'J_1': [],
        'SU(2)_W': [],
        'SU(3)_colour': [],
        'extras_iso_col_mix': [],
        'extras_sigmaX_isospin': [],
        'extras_sigmaX_colour': [],
        'extras_sigmaX_iso_col_mix': [],
    }
    for elt in centralizer:
        cls = classify_element(elt)
        if cls.startswith("J_1"):
            in_centralizer['J_1'].append(cls)
        elif cls.startswith("SU(2)_W"):
            in_centralizer['SU(2)_W'].append(cls)
        elif cls.startswith("SU(3)"):
            in_centralizer['SU(3)_colour'].append(cls)
        elif cls.startswith("isospin-colour mixing"):
            in_centralizer['extras_iso_col_mix'].append(cls)
        elif cls.startswith("chirality_X x isospin "):
            in_centralizer['extras_sigmaX_isospin'].append(cls)
        elif cls.startswith("chirality_X x colour"):
            in_centralizer['extras_sigmaX_colour'].append(cls)
        elif cls.startswith("chirality_X x isospin-colour"):
            in_centralizer['extras_sigmaX_iso_col_mix'].append(cls)

    print(f"  Conjecture Hermitian generators in centralizer:")
    print(f"    J_1                                : {len(in_centralizer['J_1']):>2d}")
    print(f"    SU(2)_W (T_a^W)                    : {len(in_centralizer['SU(2)_W']):>2d}")
    print(f"    SU(3)_colour (Gell-Manns)          : {len(in_centralizer['SU(3)_colour']):>2d}")
    n_conjecture = (len(in_centralizer['J_1'])
                    + len(in_centralizer['SU(2)_W'])
                    + len(in_centralizer['SU(3)_colour']))
    print(f"    Subtotal                           : {n_conjecture:>2d}")
    print()
    print(f"  Missing from centralizer (conjecture but not in centralizer):")
    print(f"    J_2 = (1/2) sigma_y (x) I (x) I    (chirality is sigma_y)")
    print(f"    J_3 = (1/2) sigma_z (x) I (x) I    (chirality is sigma_z)")
    print(f"    K_1, K_2, K_3 (anti-Hermitian boosts; excluded from u(12))")
    print(f"    U(1) overall phase  (= trace; outside su(12))")
    print()

    # ── Step 3: characterise the extras ────────────────────────────────
    print("-" * 70)
    print("Step 3: 'extra' centralizer generators (NOT in conjecture's algebra)")
    print("-" * 70)
    print()
    n_iso_col_mix = len(in_centralizer['extras_iso_col_mix'])
    n_sigmaX_iso = len(in_centralizer['extras_sigmaX_isospin'])
    n_sigmaX_col = len(in_centralizer['extras_sigmaX_colour'])
    n_sigmaX_full = len(in_centralizer['extras_sigmaX_iso_col_mix'])
    n_extras = n_iso_col_mix + n_sigmaX_iso + n_sigmaX_col + n_sigmaX_full
    print(f"  Isospin-colour mixings (I_2 (x) sigma_a (x) lambda_b):     "
          f"{n_iso_col_mix:>2d}  (predicted 24)")
    print(f"  Chirality-X x isospin  (sigma_x (x) sigma_a (x) I_3):       "
          f"{n_sigmaX_iso:>2d}  (predicted 3)")
    print(f"  Chirality-X x colour   (sigma_x (x) I_2 (x) lambda_a):     "
          f"{n_sigmaX_col:>2d}  (predicted 8)")
    print(f"  Chirality-X x iso-col  (sigma_x (x) sigma_a (x) lambda_b): "
          f"{n_sigmaX_full:>2d}  (predicted 24)")
    print(f"  ----------------------------------------------------------------")
    print(f"  Total extras                                                "
          f"{n_extras:>2d}  (predicted 59)")
    print()

    # ── Step 4: structural conclusion ──────────────────────────────────
    print("-" * 70)
    print("Step 4: structural conclusion")
    print("-" * 70)
    print()
    print(f"  Discrete centralizer in su(12):                {len(centralizer)}")
    print(f"  Conjecture Hermitian generators in centralizer: {n_conjecture}")
    print(f"  Extra generators (commute with tick, not in conjecture): {n_extras}")
    print()
    print(f"  Strict containment confirmed: the conjecture's su(3) (+)")
    print(f"  su(2) (+) <J_1> subalgebra is a {n_conjecture}-dim subset of")
    print(f"  the {len(centralizer)}-dim discrete-level centralizer.  The")
    print(f"  remaining 4 Hermitian generators in Eq.~(137) (J_2, J_3 from")
    print(f"  so(3,1)'s rotation subgroup) are continuum-emergent and do")
    print(f"  NOT commute with the discrete bipartite tick rule.")
    print()
    print(f"  The {n_extras} extras are tensor-product mixings between the")
    print(f"  conjecture's factors (isospin x colour, chirality_x x isospin,")
    print(f"  chirality_x x colour, full triple-mixings).  None correspond")
    print(f"  to SM-gauge-invariant operators: each one couples factors")
    print(f"  that the conjecture treats as independent.")
    print()
    print("Phase 3 result class: PART -- strict containment $\\supseteq$")
    print("confirmed at the discrete-Hermitian level.  Equality $=$ requires")
    print("imposing continuum-emergent constraints (Lorentz from O_h-averaging,")
    print("basis-permutation S_3 on colour, possibly others) that this script")
    print("does not impose.  Identifying which natural continuum-emergent")
    print("constraints reduce the 71-dim centralizer to the conjecture's 18 is")
    print("the open follow-up to this phase.")


if __name__ == '__main__':
    report()
