"""
su3_generation_from_colour_memory.py

Phase 2: determine which Lie subalgebra of su(3) is generated by
candidate extended tick rules on the per-site colour C^3.

Structural setting.

The proposed colour-memory mechanism (CLAUDE.md, Paper II Phase 2):
the per-site colour amplitude (c_1, c_2, c_3) in C^3 tracks "which
spatial direction V_j was traversed in the most recent tick."  For
this memory to accumulate, the tick rule must apply a non-trivial
unitary U_j on the colour C^3 when the wavefunction traverses V_j.

By the S_3 basis symmetry of the lattice's generators
{V_1, V_2, V_3}, U_j is the j-conjugate of U_1: U_j = P_(1->j) *
U_1 * P_(1->j)^{-1} where P_(1->j) is the colour-basis permutation
that sends |1> to |j>.

The question this script answers: starting from X_1 = -i log U_1 (a
Hermitian traceless 3x3 matrix in su(3)) and its two S_3 conjugates
X_2, X_3, what Lie subalgebra of su(3) is generated by Lie-bracket
closure?

The work plan's exit criteria allow for three terminal subalgebras:

  - dim 0:   trivial tick, no colour dynamics
  - dim 2:   Cartan (just lambda_3 and lambda_8) -- abelian, the
             continuous version of the discrete Z_3 sublattice
             finding of automorphism_rgb_su3.py
  - dim 3:   one of the su(2) subalgebras of su(3)
  - dim 8:   full su(3)

Each routes Phase 2's audit row differently:

  - dim 0 / 2: PART or FAIL (lattice generates only the Cartan
               that is already the abelian closure of the discrete
               RGB Z_3; the full su(3) of Eq.~(137) exists only as
               a global symmetry, not as a dynamically-generated
               structure)
  - dim 3:     PART (a non-trivial subalgebra is generated, but
               not the full su(3))
  - dim 8:     PASS (the natural colour-memory tick rule generates
               the full su(3) as required by Eq.~(137))

The candidates enumerated below cover the structurally-distinct
natural physical readings of "colour-memory update."

Predicted outcomes (verified by this script):

  C1 trivial (X_1 = 0)                           : dim 0
  C2 diagonal phase (X_1 = lambda_8)             : dim 2 (Cartan)
  C3 single imag off-diagonal (X_1 = lambda_2)   : dim 3 (su(2)_imag)
  C4 single real off-diagonal (X_1 = lambda_1)   : dim 3 (one su(2))
  C5 rotate-toward-|1> imag (X_1 = lambda_2+lambda_5)
                                                 : dim 3 (su(2)_imag)
  C6 rotate-toward-|1> real (X_1 = lambda_1+lambda_4)
                                                 : dim 8 (full su(3))

Conclusion.  The framework's most physically natural colour-memory
tick rule (rotation that mixes amplitude from the other components
into |j> coherently, i.e., via real-symmetric off-diagonal
generators) generates the full su(3) by Lie-bracket closure.
Diagonal-only and imaginary-antisymmetric-only readings yield
strict subalgebras.  The lattice DOES support full su(3) as a
dynamical generation, not merely as a global symmetry --- but only
for the right choice of colour-memory unitary.
"""

import sympy as sp
from sympy import I, Matrix, eye, sqrt, simplify, Rational


def gell_mann_matrices():
    """Eight Gell-Mann generators of su(3).  Hermitian, traceless,
    normalised so [lambda_a, lambda_b] = 2i f_{abc} lambda_c."""
    L1 = Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 0]])
    L2 = Matrix([[0, -I, 0], [I, 0, 0], [0, 0, 0]])
    L3 = Matrix([[1, 0, 0], [0, -1, 0], [0, 0, 0]])
    L4 = Matrix([[0, 0, 1], [0, 0, 0], [1, 0, 0]])
    L5 = Matrix([[0, 0, -I], [0, 0, 0], [I, 0, 0]])
    L6 = Matrix([[0, 0, 0], [0, 0, 1], [0, 1, 0]])
    L7 = Matrix([[0, 0, 0], [0, 0, -I], [0, I, 0]])
    L8 = (1 / sqrt(3)) * Matrix([[1, 0, 0], [0, 1, 0], [0, 0, -2]])
    return [L1, L2, L3, L4, L5, L6, L7, L8]


def colour_permutation(perm):
    """3x3 permutation matrix P with P|k> = |perm[k]>.

    `perm` is a list of length 3, perm[k] is the image of k under
    the permutation, 0-indexed."""
    M = sp.zeros(3, 3)
    for k in range(3):
        M[perm[k], k] = 1
    return M


def s3_conjugates(X):
    """Return the S_3 orbit of X under the three permutations sending
    1 to {1, 2, 3} respectively (0-indexed: {0, 1, 2}).

    For the colour basis convention |1>, |2>, |3>:
      P(1->1) = identity
      P(1->2) = transposition (1 2): swap |1> and |2>
      P(1->3) = transposition (1 3): swap |1> and |3>

    Conjugation by P sends an operator labelled by "spatial direction
    1" to the corresponding operator labelled by "spatial direction j"."""
    P_id = colour_permutation([0, 1, 2])
    P_12 = colour_permutation([1, 0, 2])
    P_13 = colour_permutation([2, 1, 0])
    return [
        simplify(P_id @ X @ P_id.inv()),
        simplify(P_12 @ X @ P_12.inv()),
        simplify(P_13 @ X @ P_13.inv()),
    ]


def matrix_to_vector(M, n=3):
    """Flatten an n x n matrix to a (n*n)-dim column vector for
    linear-algebra computations."""
    return Matrix([[M[i, j]] for i in range(n) for j in range(n)])


def matrix_rank_of_set(matrices, n=3):
    """Compute the dimension of the linear span of a list of n x n
    matrices."""
    if not matrices:
        return 0
    vectors = [matrix_to_vector(M, n) for M in matrices]
    big = sp.Matrix.hstack(*vectors)
    return big.rank()


def is_in_span(M, basis, n=3, current_rank=None):
    """Whether M is in the linear span of the basis matrices."""
    if current_rank is None:
        current_rank = matrix_rank_of_set(basis, n)
    new_rank = matrix_rank_of_set(basis + [M], n)
    return new_rank == current_rank


def commutator(A, B):
    return simplify(A @ B - B @ A)


def is_zero_matrix(M):
    return all(simplify(e) == 0 for e in M)


def lie_closure(generators, max_iter=10):
    """Iteratively close `generators` under Lie brackets.  Returns a
    minimal linearly-independent basis of the closure."""
    # Drop any zero generators and reduce to a linearly-independent set
    basis = []
    for G in generators:
        if is_zero_matrix(G):
            continue
        if not is_in_span(G, basis):
            basis.append(G)

    if not basis:
        return []

    for iteration in range(max_iter):
        current_rank = matrix_rank_of_set(basis)
        added = False
        # Compute pairwise commutators; add any that increase the rank
        new_basis = list(basis)
        for i in range(len(basis)):
            for j in range(i + 1, len(basis)):
                C = commutator(basis[i], basis[j])
                if is_zero_matrix(C):
                    continue
                if not is_in_span(C, new_basis, current_rank=current_rank):
                    new_basis.append(C)
                    current_rank += 1
                    added = True
        basis = new_basis
        if not added:
            break

    return basis


def classify_subalgebra(basis):
    """Identify which subalgebra of su(3) the closure represents.

    Returns a human-readable label based on the dimension and a
    structural fingerprint."""
    n = len(basis)
    if n == 0:
        return "trivial (dim 0)"
    if n == 2:
        return "Cartan subalgebra h (dim 2; abelian; span{lambda_3, lambda_8})"
    if n == 3:
        # Check if it's the "imaginary" su(2) subalgebra {lambda_2, lambda_5, lambda_7}
        # or another su(2) (could be any 3-dim Lie subalgebra of su(3))
        return "su(2) subalgebra of su(3) (dim 3)"
    if n == 4:
        return "intermediate subalgebra (dim 4)"
    if n == 5:
        return "intermediate subalgebra (dim 5)"
    if n == 6:
        return "intermediate subalgebra (dim 6)"
    if n == 7:
        return "intermediate subalgebra (dim 7)"
    if n == 8:
        return "full su(3) (dim 8)"
    return f"unexpected dimension (dim {n})"


def candidate_X1_set():
    """Return the list of candidate X_1's (Hermitian traceless 3x3
    matrices), labelled."""
    L = gell_mann_matrices()
    lam1, lam2, lam3, lam4, lam5, lam6, lam7, lam8 = L

    return [
        ("C1 trivial (X_1 = 0)",
         sp.zeros(3, 3)),
        ("C2 diagonal phase (X_1 = lambda_8)",
         lam8),
        ("C2' diagonal phase singling out |1> (X_1 = P_1 - I/3)",
         Matrix([[Rational(2, 3), 0, 0],
                 [0, Rational(-1, 3), 0],
                 [0, 0, Rational(-1, 3)]])),
        ("C3 single imag off-diagonal (X_1 = lambda_2)",
         lam2),
        ("C4 single real off-diagonal (X_1 = lambda_1)",
         lam1),
        ("C5 rotate-toward-|1> imag (X_1 = lambda_2 + lambda_5)",
         lam2 + lam5),
        ("C6 rotate-toward-|1> real (X_1 = lambda_1 + lambda_4)",
         lam1 + lam4),
        ("C7 mixed Cartan + real off-diag (X_1 = lambda_8 + lambda_1)",
         lam8 + lam1),
    ]


def analyse_candidate(name, X1):
    """Compute the S_3 orbit, the Lie-bracket closure, and the
    classification for a single candidate X_1."""
    orbit = s3_conjugates(X1)
    closure = lie_closure(orbit)
    dim = len(closure)
    label = classify_subalgebra(closure)
    return orbit, closure, dim, label


def report():
    print("=" * 70)
    print("Phase 2: SU(3) generation from natural colour-memory tick rules")
    print("=" * 70)
    print()
    print("For each candidate X_1 (= -i log U_1, a Hermitian traceless 3x3),")
    print("compute the S_3 orbit {X_1, X_2, X_3} under colour-basis")
    print("transpositions, then close under Lie brackets.  Report the")
    print("dimension of the generated subalgebra.")
    print()

    summary_rows = []

    for name, X1 in candidate_X1_set():
        print("-" * 70)
        print(f"Candidate: {name}")
        print("-" * 70)
        print()

        orbit, closure, dim, label = analyse_candidate(name, X1)

        print(f"  S_3 orbit dimension (span of X_1, X_2, X_3): "
              f"{matrix_rank_of_set(orbit)}")
        print(f"  Lie closure dimension:                       {dim}")
        print(f"  Classification:                              {label}")
        print()

        summary_rows.append((name, matrix_rank_of_set(orbit), dim, label))

    # ── Summary table ───────────────────────────────────────────────────
    print("=" * 70)
    print("Summary")
    print("=" * 70)
    print()
    print(f"{'Candidate':<60s} | {'Orbit':<6s} | {'Closure':<8s}")
    print("-" * 80)
    for name, orbit_dim, closure_dim, label in summary_rows:
        print(f"{name:<60s} | {orbit_dim:<6d} | {closure_dim:<8d}")
    print()
    print("Outcome classes (per work-plan exit criteria):")
    print("  dim 0:  trivial (no colour dynamics)")
    print("  dim 2:  Cartan subalgebra only (abelian; abelian closure of")
    print("          discrete RGB Z_3; same as automorphism_rgb_su3.py)")
    print("  dim 3:  one su(2) subalgebra (partial)")
    print("  dim 8:  full su(3) (PASS for Eq.~(137)'s SU(3) factor)")
    print()

    # ── Structural conclusion ──────────────────────────────────────────
    print("-" * 70)
    print("Structural conclusion")
    print("-" * 70)
    print()
    print("  The lattice supports multiple natural colour-memory tick rules,")
    print("  and the algebra generated depends sensitively on which.  Three")
    print("  structurally distinct cases:")
    print()
    print("  (i)  Diagonal-only updates (a tick along V_j applies a phase to")
    print("       colour component j with trace-zero correction) generate")
    print("       only the Cartan subalgebra of su(3).  This matches the")
    print("       discrete RGB sub-lattice finding (Z_3 -> Cartan torus)")
    print("       from automorphism_rgb_su3.py.")
    print()
    print("  (ii) Single-plane off-diagonal updates (a tick along V_j")
    print("       rotates one pair of colour components, real or imaginary)")
    print("       generate an su(2) subalgebra of su(3).  The S_3 orbit")
    print("       carries all three planes' rotations, which close to one")
    print("       3-dim subalgebra under Lie brackets.")
    print()
    print("  (iii) Two-plane real-symmetric off-diagonal updates --- the")
    print("        'rotate toward |j>' reading where a tick along V_j mixes")
    print("        amplitude from BOTH other components into |j> via real")
    print("        symmetric generators (lambda_1 + lambda_4 for j=1, and")
    print("        S_3 conjugates) --- generate the FULL su(3) under")
    print("        Lie-bracket closure.")
    print()
    print("  The 'rotate-toward-|j> real symmetric' reading is the most")
    print("  natural physical realisation of colour memory in the framework:")
    print("  it implements 'most recent tick was along V_j' as a coherent")
    print("  unitary rotation of the colour amplitude toward |j> in both")
    print("  off-diagonal planes simultaneously.  This reading lands the")
    print("  full su(3) generation as a derived feature of the lattice's")
    print("  dynamics, not merely as a global symmetry of the trivial")
    print("  extension.")
    print()
    print("  Phase 2 outcome class: PASS for the natural physical reading,")
    print("  PART for the more restrictive readings.  The lattice's")
    print("  structural admission of full su(3) is established; which")
    print("  specific colour-memory mechanism the framework selects in its")
    print("  continuum limit is a question for downstream phases (Phase 3")
    print("  equality vs containment, and any future paper on the colour-")
    print("  memory operator's quantitative form).")


if __name__ == '__main__':
    report()
